---
name: Kustomize - Deploy
description: This action will build kustomize manifests and deploy.
inputs:
  images:
    required: true
  kustomize_directory:
    required: true
  kustomize_output_file:
    required: true
  github_token:
    required: true
  destination_repo:
    required: true
  destination_folder:
    required: true
  commit_message:
    required: true
runs:
  using: composite
  steps:
  - uses: imranismail/setup-kustomize@v2
  - uses: docker/metadata-action@v4
    id: meta
    with:
      images: ${{ inputs.images }}
      tags: |
        type=sha,enable=true,prefix=,format=short
  - run: |
      pushd "${DIR}"
        kustomize edit set image "exsules/service=${IMAGE}"
        kustomize build -o ../../"${OUTPUT_FILE}"
      popd
    shell: bash
    env:
      IMAGE: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
      DIR: ${{ inputs.kustomize_directory }}
      OUTPUT_FILE: ${{ inputs.kustomize_output_file }}
  - uses: dmnemec/copy_file_to_another_repo_action@main
    env:
      API_TOKEN_GITHUB: ${{ inputs.github_token }}
    with:
      source_file: ${{ inputs.kustomize_output_file }}
      destination_repo: ${{ inputs.destination_repo }}
      destination_folder: ${{ inputs.destination_folder }}
      user_email: "16393509+exsules-bot@users.noreply.github.com"
      user_name: "exsules-bot"
      commit_message: ${{ inputs.commit_message }}
