---
name: Docker - Build
description: This action runs `docker build`.
inputs:
  context:
    default: .
    required: false
  file:
    default: Dockerfile
    required: false
  qemu:
    default: false
    required: false
  images:
    required: true
  push:
    default: false
    required: false
runs:
  using: composite
  steps:
  - uses: docker/setup-qemu-action@v2
    if: inputs.qemu == 'true'
  - uses: docker/setup-buildx-action@v2
  - uses: docker/metadata-action@v4
    id: meta
    with:
      images: ${{ inputs.images }}
      tags: |
        type=sha,enable=true,prefix=,format=short
  - uses: docker/build-push-action@v4
    with:
      context: ${{ inputs.context }}
      file: ${{ inputs.file }}
      push: ${{ inputs.push == 'true' }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
