---
name: Go - Build
description: |
  This action runs `go build` over the cmd directory and then verifies
  that there are no differences from running the tool.
inputs:
  working_directory:
    description: The directory with the root of the project.
    default: .
    required: false
  binary_name:
    description: The name of the binary to build.
    required: true
  cgo_enabled:
    default: 0
    required: false
runs:
  using: composite
  steps:
  - name: Set repo_path
    id: repo_path
    shell: bash
    run: echo "::set-output name=repo_path::github.com/$GITHUB_REPOSITORY"
  - name: Get current ref
    id: current_ref
    shell: bash
    run: echo "::set-output name=current_ref::$(git rev-parse --short HEAD)"
  - name: Run Go Build
    env:
      SHORT_SHA: ${{ steps.current_ref.outputs.current_ref }}
      BINARY_NAME: ${{ inputs.binary_name }}
      CGO_ENABLED: ${{ inputs.cgo_enabled }}
    shell: bash
    working-directory: ${{ inputs.working_directory }}
    run: >-
      go build -ldflags "-s -w"
      -ldflags "-X github.com/${GITHUB_REPOSITORY}/version.GitCommit=${SHORT_SHA} -X github.com/exsules/pkg/logging.GitCommitID=${SHORT_SHA}"
      -o ${BINARY_NAME}
