---
name: Go - Lint
description: Runs golangci-lint over the working tree.
inputs:
  working_directory:
    default: .
    required: false
runs:
  using: composite
  steps:
  - id: golangci_configuration
    uses: andstor/file-existence-action@v3
    with:
      files: .golangci.yaml
  - uses: golangci/golangci-lint-action@v6
    if: steps.golangci_configuration.outputs.files_exists == 'true'
    with:
      version: v1.58.1
      skip-pkg-cache: true
      skip-build-cache: false
