---
name: GCR - Login
description: This action runs `docker login` for various registries (only eu.gcr.io for now)
inputs:
  username:
    description: Username to login with
    required: true
  password:
    description: Password to use
    required: true
runs:
  using: composite
  steps:
  - uses: docker/login-action@v3
    with:
      registry: registry.exsules.dev
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
