---
name: GCR - Login
description: This action runs `docker login` for various registries (only eu.gcr.io for now)
inputs:
  workload_identity_provider:
    description: The workload identity provider in gcp.
    required: true
  service_account:
    description: Service Account to use.
    required: true
runs:
  using: composite
  steps:
  - id: auth
    uses: google-github-actions/auth@v0
    with:
      workload_identity_provider: ${{ inputs.workload_identity_provider }}
      service_account: ${{ inputs.service_account }}
      token_format: access_token
  - uses: docker/login-action@v2
    with:
      registry: eu.gcr.io
      username: oauth2accesstoken
      password: ${{ steps.auth.outputs.access_token }}
