---
name: GCR - Login
description: This action runs `docker login` for various registries (only eu.gcr.io for now)
runs:
  using: composite
  steps:
  - id: auth
    uses: google-github-actions
    with:
      workload_identity_provider: projects/431375282776/locations/global/workloadIdentityPools/github-actions/providers/github-actions
      service_account: github-actions-gcr@exsules-lab.iam.gserviceaccount.com
      token_format: access_token
  - uses: docker/login-action@v2
    with:
      registry: eu.gcr.io
      username: 'oauth2accesstoken'
      password: '${{ steps.auth.outputs.access_token }}'
